# **Numpy Array Basics**

### Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.

In [2]:
import numpy as np

In [3]:
# Creating an integer array with explicit dtype, which is not necessary.
int_array = np.array([1, 2, 3], dtype=np.int32)
int_array


array([1, 2, 3])

In [5]:
# Create an 2D array
original_array = np.array([[1, 2, 3],
 [4, 5, 6]])
original_array


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Creating a 3D array (Tensor) # Dimension: 3 , Shape: (2, 2, 2)
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## `linspace()` 
- linspace() is a NumPy function that is used to create an array of evenly spaced numbers over a specified interval. It is particularly useful when you want to generate a specific number of points between two values. The syntax for linspace() is as follows:

 ### `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)`


In [7]:
# Create an array of 10 equally spaced values from 0 to 1
linspace_arr = np.linspace(0, 1, 10)
linspace_arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## `logspace()`
- logspace() function in NumPy is used to create an array of numbers that are evenly spaced on a logarithmic scale. This is particularly useful when you need a set of numbers that are evenly spaced in a logarithmic space, such as for generating logarithmic plots.The syntax for logspace() is as follows:

### `np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)`

In [8]:
# Create an array of 5 values spaced logarithmically from 1 to 100
logspace_arr = np.logspace(0, 2, 5)
logspace_arr


array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

## `np.arange()`

In [9]:
 # Create an array of values from 0 to 9 with a step size of 2
arange_arr = np.arange(0, 10, 2)
arange_arr


array([0, 2, 4, 6, 8])

## `np.zeros()`

In [10]:
 # Create a 3x3 array filled with zeros
zeros_arr = np.zeros((3, 3))
zeros_arr


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## `np.ones()`

In [12]:
# Create a 2x4 array filled with ones
ones_arr = np.ones((2, 4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Create a new array filled with zeros,
# matching the shape and data type of the original array
zeros_array = np.zeros_like(original_array)
zeros_array


array([[0, 0, 0],
       [0, 0, 0]])

In [14]:
# Create a new array filled with zeros,
# matching the shape and data type of the original array
zeros_array = np.zeros_like(original_array)
zeros_array


array([[0, 0, 0],
       [0, 0, 0]])

## NumPy Arrays from Lists:

In [18]:
# Creating a 1D array from a Python list
my_list = [1, 2, 3, 4, 5]
array_1d = np.array(my_list)
print("1D Array:", array_1d)


1D Array: [1 2 3 4 5]


In [19]:
# Creating a 2D array from a nested list
my_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(my_nested_list)
print("2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##  Array Dimension and Shapes


In [20]:
 # Creating a 1D array (Vector)
arr_1d = np.array([1, 2, 3])
# Dimesion: 1 , Shape: (3,), Size: 3
print(f"Dimension: {arr_1d.ndim}, Shape: {arr_1d.shape}, size: {arr_1d.size}")


Dimension: 1, Shape: (3,), size: 3


In [31]:
a = np.array(range(10), float)
a = a.reshape((5, 2))
a.shape

(5, 2)

In [32]:
a.ndim

2

## Array Slicing and Indexing:

In [35]:
arr = np.array([10, 20, 30, 40, 50])

# Slicing the array to create a new array
sliced_array = arr[1:4] # Slice from index 1 to 3 (exclusive) [20,30,40]
sliced_array

array([20, 30, 40])

In [36]:
# Slicing the array to create a new array
sliced_array = arr[1:4] # Slice from index 1 to 3 (exclusive) [20,30,40]
sliced_array

array([20, 30, 40])

In [37]:
# Slicing the array to create a new array
sliced_array = arr[1:4] # Slice from index 1 to 3 (exclusive) [20,30,40]
sliced_array

array([20, 30, 40])

In [38]:
# Slicing the array to create a new array
sliced_array = arr[1:4] # Slice from index 1 to 3 (exclusive) [20,30,40]
sliced_array

array([20, 30, 40])

In [39]:
# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing along rows and columns
sliced_array = arr_2d[1:3, 0:2] # Slice a 2x2 subarray: [[4, 5], [7, 8]]
sliced_array

array([[4, 5],
       [7, 8]])

In [40]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing elements from index 2 to index 5 (exclusive)
sliced_array = array_1d[2:5]
print("Sliced 1D Array:", sliced_array)

# Slicing elements from the beginning up to index 6
sliced_array_start = array_1d[:6]
print("Sliced 1D Array from the start:", sliced_array_start)

# Slicing elements from index 5 to the end
sliced_array_end = array_1d[5:]
print("Sliced 1D Array till the end:", sliced_array_end)

# Using a step in the slice
sliced_array_step = array_1d[1:8:2]  # start:stop:step
print("Sliced 1D Array with a step of 2:", sliced_array_step)


Sliced 1D Array: [3 4 5]
Sliced 1D Array from the start: [1 2 3 4 5 6]
Sliced 1D Array till the end: [ 6  7  8  9 10]
Sliced 1D Array with a step of 2: [2 4 6 8]


In [41]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing elements from rows 0 to 1 and columns 1 to 2
sliced_2d_array = array_2d[0:2, 1:3]
print("Sliced 2D Array:")
print(sliced_2d_array)

# Slicing elements from all rows and column 2
sliced_2d_array_column = array_2d[:, 2]
print("Sliced 2D Array with all rows and column 2:", sliced_2d_array_column)

# Slicing elements from row 1 and all columns
sliced_2d_array_row = array_2d[1, :]
print("Sliced 2D Array with row 1 and all columns:", sliced_2d_array_row)


Sliced 2D Array:
[[2 3]
 [5 6]]
Sliced 2D Array with all rows and column 2: [3 6 9]
Sliced 2D Array with row 1 and all columns: [4 5 6]
