# Array Operations

In [1]:
import numpy as np

## `Element-wise Operations`:

In [2]:

# Element-wise operations
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([6, 7, 8, 9, 10])

# Addition
result_addition = array_a + array_b
print("Element-wise Addition:", result_addition)

# Subtraction
result_subtraction = array_b - array_a
print("Element-wise Subtraction:", result_subtraction)

# Multiplication
result_multiplication = array_a * array_b
print("Element-wise Multiplication:", result_multiplication)

# Division
result_division = array_b / array_a
print("Element-wise Division:", result_division)


Element-wise Addition: [ 7  9 11 13 15]
Element-wise Subtraction: [5 5 5 5 5]
Element-wise Multiplication: [ 6 14 24 36 50]
Element-wise Division: [6.         3.5        2.66666667 2.25       2.        ]


## `Broadcasting`:

In [3]:
# Broadcasting in NumPy
array_c = np.array([[1, 2, 3], [4, 5, 6]])
scalar_value = 2

# Adding a scalar to a 2D array
result_broadcasting = array_c + scalar_value
print("Broadcasting Result:", result_broadcasting)


Broadcasting Result: [[3 4 5]
 [6 7 8]]


## `Array-wise Operations`:

In [5]:
# Array-wise operations
array_d = np.array([[1, 2], [3, 4]])
array_e = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result_matrix_multiplication = np.matmul(array_d, array_e)
print("Matrix Multiplication Result:")
print(result_matrix_multiplication)

# Dot product
result_dot_product = np.dot(array_d, array_e)
print("Dot Product Result:")
print(result_dot_product)


Matrix Multiplication Result:
[[19 22]
 [43 50]]
Dot Product Result:
[[19 22]
 [43 50]]


## `Mathematical and Statistical Functions`:

In [7]:
# Mathematical and statistical functions
array_f = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
result_mean = np.mean(array_f)
print("Mean of the Array:", result_mean)

# Median
result_median = np.median(array_f)
print("Median of the Array:", result_median)

# Standard deviation
result_std_deviation = np.std(array_f)
print("Standard Deviation of the Array:", result_std_deviation)


Mean of the Array: 5.5
Median of the Array: 5.5
Standard Deviation of the Array: 2.8722813232690143


## `Universal functions`

In [10]:
arr = np.array([1, 2, 3, 4, 5])

sqrt_arr = np.sqrt(arr) # Square Root
print(f'square root - {sqrt_arr}')
exp_arr = np.exp(arr) # Exponential
print(f'exponential array - {exp_arr}')

square root - [1.         1.41421356 1.73205081 2.         2.23606798]
exponential array - [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
