# Copies and Views

## `Understanding Views and Copies`:

In [2]:
import numpy as np



In [3]:
# Creating a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Creating a view of the original array
array_view = original_array.view()
print("View Array:", array_view)

# Creating a copy of the original array
array_copy = original_array.copy()
print("Copied Array:", array_copy)


View Array: [1 2 3 4 5]
Copied Array: [1 2 3 4 5]


## View versus Copy:

In [4]:
# Modifying the view
array_view[0] = 100
print("Modified View Array:", array_view)
print("Original Array after modifying view:", original_array)

# Modifying the copy
array_copy[0] = 200
print("Modified Copied Array:", array_copy)
print("Original Array after modifying copy:", original_array)


Modified View Array: [100   2   3   4   5]
Original Array after modifying view: [100   2   3   4   5]
Modified Copied Array: [200   2   3   4   5]
Original Array after modifying copy: [100   2   3   4   5]


## Slicing and Views:

In [6]:
# Creating a NumPy array
original_array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a view of a slice of the original 2D array
array_view_slice = original_array_2d[:, :2]
print("View of a Slice of the 2D Array:")
print(array_view_slice)

# Modifying the view of the slice
array_view_slice[0, 0] = 100
print("Modified View of a Slice of the 2D Array:")
print(array_view_slice)
print("Original 2D Array after modifying view of the slice:")
print(original_array_2d)


View of a Slice of the 2D Array:
[[1 2]
 [4 5]]
Modified View of a Slice of the 2D Array:
[[100   2]
 [  4   5]]
Original 2D Array after modifying view of the slice:
[[100   2   3]
 [  4   5   6]]


## Sorting and Searching:

In [7]:
import numpy as np

# Sorting an array
array_to_sort = np.array([3, 1, 2, 4, 5])
sorted_array = np.sort(array_to_sort)
print("Sorted Array:", sorted_array)

# Searching for elements in a sorted array
index_of_value = np.where(sorted_array == 4)
print("Index of value 4 in the sorted array:", index_of_value)


Sorted Array: [1 2 3 4 5]
Index of value 4 in the sorted array: (array([3], dtype=int64),)


## Unique Elements

In [8]:
# Finding unique elements in an array
array_with_duplicates = np.array([1, 2, 3, 2, 4, 1, 5, 4])
unique_elements = np.unique(array_with_duplicates)
print("Unique Elements in the Array:", unique_elements)


Unique Elements in the Array: [1 2 3 4 5]


## Set Operations:

In [9]:
# Performing set operations on arrays
array_set1 = np.array([1, 2, 3, 4, 5])
array_set2 = np.array([4, 5, 6, 7, 8])

# Union of two arrays
union_array = np.union1d(array_set1, array_set2)
print("Union of two arrays:", union_array)

# Intersection of two arrays
intersection_array = np.intersect1d(array_set1, array_set2)
print("Intersection of two arrays:", intersection_array)

# Set difference of two arrays
set_diff_array = np.setdiff1d(array_set1, array_set2)
print("Set difference of two arrays:", set_diff_array)


Union of two arrays: [1 2 3 4 5 6 7 8]
Intersection of two arrays: [4 5]
Set difference of two arrays: [1 2 3]


## Vector stacking

In [10]:
# Vector stacking in NumPy
array_x = np.array([1, 2, 3])
array_y = np.array([4, 5, 6])

# Vertical stacking
vertical_stack = np.vstack((array_x, array_y))
print("Vertical Stack:")
print(vertical_stack)

# Horizontal stacking
horizontal_stack = np.hstack((array_x, array_y))
print("Horizontal Stack:")
print(horizontal_stack)


Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]
